// import img1 from './assets/images/main-1.jpg';
// import './components/calendar/calendar.js';
import 'air-datepicker/dist/js/datepicker.min.js';
import 'air-datepicker/dist/css/datepicker.min.css';
import './assets/styles/main.scss';
import './rpie.js';
import './pages/room-dets.js';
import './pages/search-room.js';
import './components/header/header.js';
import './components/calendar/calendar.js';
import './components/guests/guests.js';
